language: python
python:
  - "3.11"
  - "3.10"
  - "3.9"
  - "3.8"
  - "pypy3"
install:
  - "pip install -r requirements-tests.txt"
  - "python setup.py install"
script: "python setup.py nosetests && flake8 attrdict tests"
after_success:
  - coveralls
